-- 프로필 테이블 (auth.users와 1:1 관계)
create table public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  full_name text,
  avatar_url text,
  updated_at timestamp with time zone default now()
);

-- 근퇴 기록
create table public.attendance (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  type text check (type in ('check_in', 'check_out')) not null,
  created_at timestamp with time zone default now() not null
);

-- 일정 공유
create table public.schedules (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  title text not null,
  description text,
  start_time timestamp with time zone not null,
  end_time timestamp with time zone not null,
  color text default '#3b82f6',
  created_at timestamp with time zone default now()
);

-- 채팅 메시지
create table public.messages (
  id bigint generated by default as identity primary key,
  sender_id uuid references public.profiles(id) on delete cascade not null,
  content text not null,
  attachment_url text,
  created_at timestamp with time zone default now()
);

-- Row Level Security (RLS) 활성화
alter table public.profiles enable row level security;
alter table public.attendance enable row level security;
alter table public.schedules enable row level security;
alter table public.messages enable row level security;

-- Profiles 정책: 모든 로그인 사용자가 모든 프로필 읽기 가능, 자신의 프로필만 수정 가능
create policy "Public profiles are viewable by everyone"
  on profiles for select
  using ( true );

create policy "Users can insert their own profile"
  on profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile"
  on profiles for update
  using ( auth.uid() = id );

-- Attendance 정책: 모든 로그인 사용자가 모든 근태 기록 읽기 가능, 자신의 기록만 생성 가능
create policy "Attendance records are viewable by everyone"
  on attendance for select
  using ( true );

create policy "Users can insert their own attendance"
  on attendance for insert
  with check ( auth.uid() = user_id );

-- Schedules 정책: 모든 로그인 사용자가 모든 일정 읽기 가능, 자신의 일정만 관리 가능
create policy "Schedules are viewable by everyone"
  on schedules for select
  using ( true );

create policy "Users can insert their own schedules"
  on schedules for insert
  with check ( auth.uid() = user_id );

create policy "Users can update their own schedules"
  on schedules for update
  using ( auth.uid() = user_id );

create policy "Users can delete their own schedules"
  on schedules for delete
  using ( auth.uid() = user_id );

-- Messages 정책: 모든 로그인 사용자가 모든 메시지 읽기 가능, 자신의 메시지만 생성 가능
create policy "Messages are viewable by everyone"
  on messages for select
  using ( true );

create policy "Users can insert their own messages"
  on messages for insert
  with check ( auth.uid() = sender_id );

-- 실시간 구독을 위한 Publication 설정 (Supabase Realtime)
-- Supabase는 기본적으로 realtime을 지원하지만, 명시적으로 설정하려면:
-- alter publication supabase_realtime add table attendance;
-- alter publication supabase_realtime add table schedules;
-- alter publication supabase_realtime add table messages;

-- 사용자 프로필 자동 생성 트리거 (회원가입 시 자동으로 profiles 테이블에 레코드 생성)
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, full_name, avatar_url)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'full_name', ''),
    coalesce(new.raw_user_meta_data->>'avatar_url', '')
  );
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
